version: "3.8"
services:
  stockmap-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - python-service
  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./static:/app/static
    command: ["python", "stockMap.py"]